### ISSUE TITLE
Duplikacja kodu w Jet

### ISSUE THREAD

**Issue by MaLiN2223** [KoloMK/MKNum#3]
Aby nie duplikować kodu fajnie by było jakoś je opakować.
Propozycja podania : 
[item.txt](https://github.com/KoloMK/MKNum/files/24780/item.txt)

**Comment by 13MaxG** [comment]
Myślałem o tym, i wymyśliłem żeby zrobić tak jak piszesz, ale taki obiekt prytawtny klasy, a publicznie zostawić sin cos, żeby było wygodnie.

**Comment by MaLiN2223** [comment]
Czyli tak jak w .txt który wysłałem?

**Comment by 13MaxG** [comment]
Dokładnie, ale raczej bez enuma. boolean wystarczy do naszego przypadku. zajmę się tym jutro.
